kind: Job
apiVersion: batch/v1
metadata:
  name: protbertfinetune
  namespace: zaiqiaoproject
  labels:
    app: protbertfinetune_app
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: protbertfinetune_app
        job-name: protbertfinetune
    spec:
      nodeSelector:
        node-role.ida/gputitan: 'true'
      restartPolicy: OnFailure
      serviceAccountName: containerroot
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '6'
              memory: 56Gi
            requests:
              cpu: '3'
              memory: 18Gi
          terminationMessagePath: /dev/termination-log
          name: modelfinetuning
          command:
            - bash
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: srv-jobmanager
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-access
              mountPath: /nfs/
          terminationMessagePolicy: File
          image: 'docker-registry.default.svc:5000/zaiqiaoproject/protbert'
          workingDir: /nfs/protbert/src
          args:
            - run_model0_finetune_1.sh
      serviceAccount: containerroot
      volumes:
        - name: nfs-access
          persistentVolumeClaim:
            claimName: zaiqiaovol1claim
      dnsPolicy: ClusterFirst